### PR TITLE
 Add kernel module signing support 

### PR DESCRIPTION
**Pull request by dsd**
Extend pesign to be able to sign kernel modules in addition to
PE executables.

We use the file extension .ko to detect when to sign it as a module.
The signing involves appending a PKCS7 message with signature, followed
by a Linux-specific module_signature structure.

This initial code supports creating attached and detached signatures,
and supports both standalone pesign and the daemon mode.

### CODE REVIEW

**Comment by dsd** [comment]
@vathpela ping - have you had a moment to look at this?

**Comment by vathpela** [comment]
Er... yes, and then apparently I failed to respond.  So mostly I like this!  There are a couple of nitpicks I have though.  I'll comment inline.

**Comment by vathpela** [comment]
I take it back - I'll comment here, it's way easier.  Is it possible to make kmod_handle_action() also implement the IMPORT_RAW_SIGNATURE|IMPORT_SATTRS and EXPORT_SATTRS methods?  These are how crypto offload modules are supported for modules that don't provide a pkcs11 library interface.  (Basically, you use "openssl dgst" to sign the exported blob, and then re-import it.)

**Comment by vathpela** [comment]
I'd still like to refactor a lot more of this, but I've pushed it to master since it is usable for some things.

**Pull request closed without merging**
